#region Copyright
// Copyright 2014 Myrcon Pty. Ltd.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#endregion
using System;

namespace Potato.Database.Shared.Builders.Modifiers {
    /// <summary>
    /// A hint modifier is inserted to any object generated by the builder
    /// when using the shorthand methods to build a query. Just lets the 
    /// serializers know it can safely ignore fields if it needs to.
    /// </summary>
    [Serializable]
    public class Implicit : Modifier {
    }
}
