using System;

namespace Procon.Database.Shared.Builders.Modifiers {
    /// <summary>
    /// A hint modifier is inserted to any object generated by the builder
    /// when using the shorthand methods to build a query. Just lets the 
    /// serializers know it can safely ignore fields if it needs to.
    /// </summary>
    [Serializable]
    public class Implicit : Modifier {
    }
}
