using System;

namespace Potato.Core.Shared.Models {
    /// <summary>
    /// Used to transport the secure information (Id, Token) generated by the token
    /// </summary>
    /// <remarks>
    ///     <para>This is kept seperate from the AcountAccessTokenModel so the intent and data are delibrerately exposed.</para>
    ///     <para>This model should be sent to an authenticated account, while most of the data within AccountAccessTokenModel should never be sent to anyone.</para>
    /// </remarks>
    [Serializable]
    public class AccessTokenTransportModel : CoreModel, IDisposable {
        /// <summary>
        /// The id of the session
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// The token which can be used to authenticate
        /// </summary>
        public String Token { get; set; }

        public void Dispose() {
            this.Id = Guid.Empty;
            this.Token = null;
        }
    }
}
