// Copyright 2011 Geoffrey 'Phogue' Green
// 
// http://www.phogue.net
//  
// This file is part of Procon 2.
// 
// Procon 2 is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Procon 2 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Procon 2.  If not, see <http://www.gnu.org/licenses/>.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Procon.Core.Interfaces.Layer.Objects {
    using Procon.Net.Protocols.Objects;
    public class Login : ProtocolObject {

        /// <summary>
        /// The username of the person accounts
        /// </summary>
        public string Username { get; set; }

        /// <summary>
        /// The salt generated by the daemon and sent back to the client
        /// </summary>
        public string Salt { get; set; }

        /// <summary>
        /// The hashed password, including the salt
        /// </summary>
        public string Hash { get; set; }

        /// <summary>
        /// The status of the authentication
        /// </summary>
        public bool Authenticated { get; set; }

        public Login() {
            this.Username = String.Empty;
            this.Salt = String.Empty;
            this.Hash = String.Empty;
            this.Authenticated = false;
        }
    }
}
