// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Myrcon.Plugins.Test.Pages
{
    using System;
    
    
    #line 1 "C:\Users\P\Documents\Projects\clients\myrcon\procon\Procon-2\src\Myrcon.Plugins.Test\Pages\IndexPageView.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class IndexPageView : IndexPageViewBase
    {
        public virtual string TransformText()
        {
            this.Write("<html>\r\n\t<head>\r\n\t\t<title>This is my title</title>\r\n\t</head>\r\n\t<body>\r\n\t\t<ul clas" +
                    "s=\"nav nav-tabs\" ng-controller=\"MenuController\">\r\n\t\t  <li ng-class=\"{ \'active\': " +
                    "Path == \'#/\' }\"><a href=\"#/\">Home</a></li>\r\n\t\t  <li ng-class=\"{ \'active\': Path =" +
                    "= \'#/about\' }\"><a href=\"#/about\">About</a></li>\r\n\t\t</ul>\r\n\t\t<div id=\"content\">\r\n" +
                    "            <div ng-view></div>\r\n\r\n            <script type=\"text/ng-template\" i" +
                    "d=\"/index.html\">\r\n                <h2>Index</h2>\r\n\t\t\t\t<p>Here\'s a variable from " +
                    "the controller: {{ SomeData }}</p>\r\n\r\n\t\t\t\t<form class=\"smart-form\" name=\"multipl" +
                    "ication\" ng-submit=\"multiplication.$valid && Submit()\">\r\n\t\t\t\t\t<header>\r\n\t\t\t\t\t\t<h" +
                    "2>Enter a number to test command architecture</h2>\r\n\t\t\t\t\t</header>\r\n\t\t\t\t\t<fields" +
                    "et>\r\n                        <section>\r\n                            <label class" +
                    "=\"input\">\r\n                                <input class=\"form-control\" type=\"inp" +
                    "ut\" placeholder=\"Enter a number to multiply it by 2\" name=\"number\" ng-model=\"Mat" +
                    "hematics.Number\" required>\r\n                            </label>\r\n              " +
                    "              <em ng-show=\"multiplication.number.$dirty && multiplication.number" +
                    ".$invalid && multiplication.number.$error.required\" class=\"ng-hide\">Please enter" +
                    " a number to multiply</em>\r\n                        </section>\r\n                " +
                    "    </fieldset>\r\n\t\t\t\t\t<footer>\r\n                        <button class=\"btn btn-p" +
                    "rimary\" ng-disabled=\"MathematicsActions.Communicating || multiplication.$invalid" +
                    "\" disabled=\"disabled\">\r\n                            <img ng-show=\"MathematicsAct" +
                    "ions.Communicating\" src=\"/assets/img/loading.gif\" class=\"ng-hide\"><i ng-hide=\"Ma" +
                    "thematicsActions.Communicating\" class=\"fa fa-arrow-right\"></i> Create\r\n         " +
                    "               </button>\r\n                    </footer>\r\n\t\t\t\t</form>\r\n\t\t\t\t\r\n\t\t\t\t" +
                    "<h3>Here\'s the result of the multiplication: {{ Mathematics.Result }}</h3>\r\n\t\t\t\t" +
                    "<div ng-if=\"Mathematics.Result != 0\">\r\n\t\t\t\t\t<p>The process this just went throug" +
                    "h:</p>\r\n\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t<li>Angular.Submit()</li>\r\n\t\t\t\t\t\t<li>Through the sandbo" +
                    "x between Procon.UI Window and this plugins iframe with postMessage</li>\r\n\t\t\t\t\t\t" +
                    "<li>Emitted via websocket to the Procon UI</li>\r\n\t\t\t\t\t\t<li>Credentials attached " +
                    "and the command, sent to a running Procon 2 C# Instance</li>\r\n\t\t\t\t\t\t<li>Deserial" +
                    "ized by Procon 2, routed to a specific connection</li>\r\n\t\t\t\t\t\t<li>Crosses the sa" +
                    "ndbox into the Plugin AppDomain</li>\r\n\t\t\t\t\t\t<li>Routes the command \"TestPluginSi" +
                    "mpleMultiplyByTwoCommand\" at https://github.com/Myrcon/Procon-2/blob/master/src/" +
                    "Myrcon.Plugins.Test/Tests/TestPluginsWebUi.cs </li>\r\n\t\t\t\t\t\t<li>Multiplies the nu" +
                    "mber.</li>\r\n\t\t\t\t\t\t<li>Reverse of above.</li>\r\n\t\t\t\t\t</ul>\r\n\t\t\t\t</div>\r\n          " +
                    "  </script>\r\n\r\n            <script type=\"text/ng-template\" id=\"/about.html\">\r\n  " +
                    "              <h2>About</h2>\r\n\t\t\t\t<p>This plugin is made by Geoff to demonstrate" +
                    " making a basic plugin UI.</p>\r\n            </script>\r\n\t\t</div>\r\n\t</body>\r\n</htm" +
                    "l>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class IndexPageViewBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
